services:
  - type: web
    name: samselt-production
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: samselt-postgres
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
    healthCheckPath: /api/health

databases:
  - name: samselt-postgres
    databaseName: samselt
    user: samselt_user
    plan: starter